### ISSUE TITLE
README is empty

### ISSUE THREAD

**Issue by Descent098** [openbao/.github#1]
Probably not a huge priority, but I just noticed that the readme for the org is empty, which leads to a broken-looking org landing page 

![image](https://github.com/openbao/.github/assets/22761705/eaf36f35-352d-40ac-9367-53886dd5904a)

If you want I can open a PR to grab the [first section](https://github.com/openbao/openbao#:~:text=OpenBao%20exists%20to,OpenBao%20steps%20in.) of the openbao readme and chuck it in the file

Thanks!

**Comment by cipherboy** [comment]
Sorry @Descent098 -- it looks like @naphelps got to this :-) if you have any modifications, feel free to open a PR!
